defaults:
  - inference_base
  - _self_

run_name_: broteina_distillation_motif
# ckpt_name: proteina_v1.7_DFS_60M_notri_motif_scaffolding.ckpt
ckpt_name: motif_uniform_chk_epoch=00000000_step=000000010400.ckpt
dataset_config_subdir: broteina
dataset: motif_scaffold_train

self_cond: True

training:
  motif_conditioning: True
  motif_conditioning_sequence_rep: True
  use_provided_motifs: True

sampling_caflow:
  sampling_mode: sc  # "vf" for ODE sampling, "sc" for SDE sampling
  sc_scale_noise: 0.45  # noise scale, used if sampling_mode == "sc"
